version: "3.8"

services:
  water-contamination-detection:
    build: .
    container_name: water_contamination_detection
    ports:
      - "8501:8501" # Access at http://localhost:8501
    volumes:
      - .:/app # Live reload — changes reflect instantly
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
