data:
  raw_path: data/raw/water_potability.csv
  processed_path: data/processed/water_classified_fixed.csv
  test_size: 0.2
  random_state: 42

features:
  names:
    - ph
    - Solids
  target: Potability

model:
  rf:
    n_estimators: 100
    random_state: 42
  svm:
    kernel: rbf
    probability: true
    random_state: 42

noise:
  ph_std: 1.5
  tds_std: 80.0

anomaly:
  ph_critical_low: 4.0
  ph_critical_high: 10.0
  tds_critical_high: 3000

output:
  model_path: water_model.pkl
  metrics_path: reports/metrics.json
  eval_metrics_path: reports/eval_metrics.json
